name: 'Get current version of a maven project'
author: https://github.com/jenspapenhagen
description: 'Get the current version of the pom package using maven evaluate'
branding:
  color: 'green'
  icon: 'git-branch'
inputs:
  path:
    required: false
    default: '.'
    description: 'Path to pom.xml file (directories only), e.g. "mavenproject/<yourproject>"'
  args:
    required: false
    default: '.'
    description: 'Additional maven command args to run, e.g. "-DskipTests"'

outputs:
  version:
    description: 'Current version defined in the pom.xml file'
  major:
    description: 'Current major version defined in the pom.xml file'
  minor:
    description: 'Current minor version defined in the pom.xml file'
  patch:
    description: 'Current patch version defined in the pom.xml file'

runs:
  using: "composite"
  # using: 'docker'
  # image: 'Dockerfile'
  # args: 
  #   - entrypoint.sh
  steps:
    - name: Get Version
      id: get-version
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_ARGS: ${{ inputs.args }}
      run: ${{github.action_path}}/entrypoint.sh
      shell: bash  
    - name: Result
      shell: bash
      run: "echo 'Version is now ${{ steps.get-version.outputs.version }}'"